name: NotchFlow
options:
  bundleIdPrefix: com.notchflow
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_HARDENED_RUNTIME: NO
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.notchflow.app
    INFOPLIST_FILE: NotchFlow/Info.plist
    PRODUCT_NAME: NotchFlow
targets:
  NotchFlow:
    type: application
    platform: macOS
    sources:
      - path: NotchFlow/Sources
        createIntermediateGroups: true
    info:
      path: NotchFlow/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.notchflow.app
        INFOPLIST_FILE: NotchFlow/Info.plist
